# Generated by Django 5.2.2 on 2025-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('admin_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_id', models.CharField(blank=True, max_length=20)),
                ('admin_name', models.CharField(blank=True, max_length=10)),
                ('admin_password', models.CharField(blank=True, max_length=100)),
                ('reg_dt', models.DateTimeField()),
                ('upd_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_user',
                'managed': False,
            },
        ),
    ]
